package Pojos;
// Generated Nov 1, 2018 12:42:32 PM by Hibernate Tools 4.3.1



/**
 * PemilikKendaraan generated by hbm2java
 */
public class PemilikKendaraan  implements java.io.Serializable {


     private String nama;
     private String email;
     private String password;

    public PemilikKendaraan() {
    }

	
    public PemilikKendaraan(String nama) {
        this.nama = nama;
    }
    public PemilikKendaraan(String nama, String email, String password) {
       this.nama = nama;
       this.email = email;
       this.password = password;
    }
   
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }


public String toJson() {

        return "{\"nama\":" + getNama()+ ",\"email\":" + getEmail()+ ",\"password\":" + getPassword()+ "}";

}}


