package pojos;
// Generated Nov 22, 2018 12:03:11 PM by Hibernate Tools 4.3.1



/**
 * PemilikBengkel generated by hbm2java
 */
public class PemilikBengkel  implements java.io.Serializable {


     private String email;
     private String nama;
     private String password;
     private String namaBengkel;
     private String alamat;
     private String jamBuka;
     private String jenisKendaraan;
     private Double longitud;
     private Double latitude;
     private String jamTutup;

    public PemilikBengkel() {
    }

	
    public PemilikBengkel(String email) {
        this.email = email;
    }
    public PemilikBengkel(String email, String nama, String password, String namaBengkel, String alamat, String jamBuka, String jenisKendaraan, Double longitud, Double latitude, String jamTutup) {
       this.email = email;
       this.nama = nama;
       this.password = password;
       this.namaBengkel = namaBengkel;
       this.alamat = alamat;
       this.jamBuka = jamBuka;
       this.jenisKendaraan = jenisKendaraan;
       this.longitud = longitud;
       this.latitude = latitude;
       this.jamTutup = jamTutup;
    }

   
   
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getNamaBengkel() {
        return this.namaBengkel;
    }
    
    public void setNamaBengkel(String namaBengkel) {
        this.namaBengkel = namaBengkel;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getJamBuka() {
        return this.jamBuka;
    }
    
    public void setJamBuka(String jamBuka) {
        this.jamBuka = jamBuka;
    }
    public String getJenisKendaraan() {
        return this.jenisKendaraan;
    }
    
    public void setJenisKendaraan(String jenisKendaraan) {
        this.jenisKendaraan = jenisKendaraan;
    }
    public Double getLongitud() {
        return this.longitud;
    }
    
    public void setLongitud(Double longitud) {
        this.longitud = longitud;
    }
    public Double getLatitude() {
        return this.latitude;
    }
    
    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }
    public String getJamTutup() {
        return this.jamTutup;
    }
    
    public void setJamTutup(String jamTutup) {
        this.jamTutup = jamTutup;
    }

    public String toJson() {
         return "{\"nama\":" + getNama()+ ",\"email\":" + getEmail() + ",\"password\":" + getPassword() + 
                 ",\"namaBengkel\":" + getNamaBengkel() + ",\"alamat\":" + getAlamat() + ",\"jamBuka\":" +getJamBuka() + 
                 ",\"jenisKendaraan\":" +  getJenisKendaraan() + ",\"longitud\":" + getLongitud() + ",\"latitude\":" + getLatitude() + 
                  ",\"jamTutup\":" + getJamTutup() + "}";

    
    }

//    public Object login(String email, String password) {
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
//    }

  
}


