package pojos;
// Generated Dec 2, 2018 10:20:07 AM by Hibernate Tools 4.3.1

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

    private int noAntrian;

    public Service() {
    }

    public Service(int noAntrian) {
        this.noAntrian = noAntrian;
    }

    public int getNoAntrian() {
        return this.noAntrian;
    }

    public void setNoAntrian(int noAntrian) {
        this.noAntrian = noAntrian;
    }

    public String toJson() {
        return "{\"noAntrian\":" + getNoAntrian() + "}";
    }

}
